### ISSUE TITLE
Error at npm start

### ISSUE THREAD

**Issue by claytron5000** [phase2/pattern-lab-starter#38]
At first I had placed the patternlab directory at the root of the site. That's where these errors come from, I moved the directory to inside the theme. The same errors persists.
```
npm ERR! PatternLabStarter@8.0.0 start: `gulp clean && gulp compile && gulp`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the PatternLabStarter@8.0.0 start script.
npm ERR! This is most likely a problem with the PatternLabStarter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp clean && gulp compile && gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls PatternLabStarter
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.5.0
npm ERR! command "/Users/me/.nvm/v0.10.25/bin/node" "/Users/me/.nvm/v0.10.25/bin/npm" "start"
npm ERR! cwd /Users/me/Sites/d8/patternlab
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/me/Sites/d8/patternlab/npm-debug.log
npm ERR! not ok code 0
```

**Comment by claytron5000** [comment]
From the log:
```
1 verbose cli [ '/Users/me/.nvm/v0.10.25/bin/node',
1 verbose cli   '/Users/me/.nvm/v0.10.25/bin/npm',
1 verbose cli   'start' ]
2 info using npm@1.3.24
3 info using node@v0.10.25
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart PatternLabStarter@8.0.0
6 info start PatternLabStarter@8.0.0
7 verbose unsafe-perm in lifecycle true
8 info PatternLabStarter@8.0.0 Failed to exec start script
9 error PatternLabStarter@8.0.0 start: `gulp clean && gulp compile && gulp`
9 error Exit status 8
10 error Failed at the PatternLabStarter@8.0.0 start script.
10 error This is most likely a problem with the PatternLabStarter package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     gulp clean && gulp compile && gulp
10 error You can get their info via:
10 error     npm owner ls PatternLabStarter
10 error There is likely additional logging output above.
11 error System Darwin 15.5.0
12 error command "/Users/me/.nvm/v0.10.25/bin/node" "/Users/me/.nvm/v0.10.25/bin/npm" "start"
13 error cwd /Users/me/Sites/d8/patternlab
14 error node -v v0.10.25
15 error npm -v 1.3.24
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]
```

**Comment by EvanLovely** [comment]
You're using node `v0.10` which is very old and not supported. Please update your node. If you have home brew you could run `brew install node`. I personally recommend [`nvm`](https://github.com/creationix/nvm) for managing node versions. 

Thanks for the bug report and trying it out!

**Comment by claytron5000** [comment]
Upgraded Node and npm:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/clayton/.nvm/versions/node/v6.2.1/bin/node',
1 verbose cli   '/Users/clayton/.nvm/versions/node/v6.2.1/bin/npm',
1 verbose cli   'bugs',
1 verbose cli   'PatternLabStarter' ]
2 info using npm@3.9.5
3 info using node@v6.2.1
4 silly fetchPackageMetaData PatternLabStarter
5 silly fetchNamedPackageData PatternLabStarter
6 silly mapToRegistry name PatternLabStarter
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'PatternLabStarter',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   name: 'PatternLabStarter',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/PatternLabStarter
11 verbose request uri https://registry.npmjs.org/PatternLabStarter
12 verbose request no auth needed
13 info attempt registry request try #1 at 4:06:01 PM
14 verbose request id cb7fb357a8a2d789
15 http request GET https://registry.npmjs.org/PatternLabStarter
16 http 404 https://registry.npmjs.org/PatternLabStarter
17 verbose headers { 'content-type': 'application/json',
17 verbose headers   'cache-control': 'max-age=0',
17 verbose headers   'content-length': '2',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Fri, 03 Jun 2016 20:06:02 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   age: '0',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-atl6245-ATL',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1464984362.020912,VS0,VE145',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 404,
18 silly get   { 'content-type': 'application/json',
18 silly get     'cache-control': 'max-age=0',
18 silly get     'content-length': '2',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Fri, 03 Jun 2016 20:06:02 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '0',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-atl6245-ATL',
18 silly get     'x-cache': 'MISS',
18 silly get     'x-cache-hits': '0',
18 silly get     'x-timer': 'S1464984362.020912,VS0,VE145',
18 silly get     vary: 'Accept-Encoding' } ]
19 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/PatternLabStarter
19 silly fetchPackageMetaData     at makeError (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
19 silly fetchPackageMetaData     at Request._callback (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
19 silly fetchPackageMetaData     at Request.self.callback (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:200:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:1067:10)
19 silly fetchPackageMetaData     at emitOne (events.js:101:20)
19 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:988:12)
19 silly fetchPackageMetaData  error for PatternLabStarter { Error: Registry returned 404 for GET on https://registry.npmjs.org/PatternLabStarter
19 silly fetchPackageMetaData     at makeError (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
19 silly fetchPackageMetaData     at Request._callback (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
19 silly fetchPackageMetaData     at Request.self.callback (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:200:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:1067:10)
19 silly fetchPackageMetaData     at emitOne (events.js:101:20)
19 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:988:12) pkgid: 'PatternLabStarter', statusCode: 404, code: 'E404' }
20 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/PatternLabStarter
20 verbose stack     at makeError (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
20 verbose stack     at Request._callback (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
20 verbose stack     at Request.self.callback (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:200:22)
20 verbose stack     at emitTwo (events.js:106:13)
20 verbose stack     at Request.emit (events.js:191:7)
20 verbose stack     at Request.<anonymous> (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:1067:10)
20 verbose stack     at emitOne (events.js:101:20)
20 verbose stack     at Request.emit (events.js:188:7)
20 verbose stack     at IncomingMessage.<anonymous> (/Users/clayton/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:988:12)
21 verbose statusCode 404
22 verbose pkgid PatternLabStarter
23 verbose cwd /Users/clayton/Sites/d8/patternlab
24 error Darwin 15.5.0
25 error argv "/Users/clayton/.nvm/versions/node/v6.2.1/bin/node" "/Users/clayton/.nvm/versions/node/v6.2.1/bin/npm" "bugs" "PatternLabStarter"
26 error node v6.2.1
27 error npm  v3.9.5
28 error code E404
29 error 404 Registry returned 404 for GET on https://registry.npmjs.org/PatternLabStarter
30 error 404
31 error 404 'PatternLabStarter' is not in the npm registry.
32 error 404 Your package name is not valid, because
33 error 404 1. name can no longer contain capital letters
34 error 404 Note that you can also install from a
35 error 404 tarball, folder, http url, or git url.
36 verbose exit [ 1, true ]```

**Comment by EvanLovely** [comment]
What command are you running? You just need to clone this repo and then run the commands in the readme inside it.
