### ISSUE TITLE
problems when npm install

### ISSUE THREAD

**Issue by cristinallamas** [phase2/pattern-lab-starter#50]
I'm not sure what to do, I've upgraded npm and node
```
node -v
v6.5.0
```
```
npm --version
3.10.7
```

```
▶ npm install
[npm-debug.log.zip](https://github.com/phase2/pattern-lab-starter/files/480228/npm-debug.log.zip)


(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:15560) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated swig@1.4.0: This package is no longer maintained
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global varstream@0.3.2 should be installed with -g
npm WARN prefer global svgicons2svgfont@5.0.0 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
npm WARN prefer global ttf2woff2@2.0.3 should be installed with -g

> fsevents@1.0.14 install /Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> ttf2woff2@2.0.3 install /Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance


> node-sass@3.10.0 install /Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.0/darwin-x64-48_binding.node
Binary downloaded and installed at /Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/node-sass/vendor/darwin-x64-48/binding.node

> spawn-sync@1.0.15 postinstall /Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/spawn-sync
> node postinstall


> node-sass@3.10.0 postinstall /Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/node-sass
> node scripts/build.js

"/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/node-sass/vendor/darwin-x64-48/binding.node" exists.
 testing binary.
Binary is fine; exiting.

> yo@1.8.5 postinstall /Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!

> PatternLabStarter@8.2.1 postinstall /Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter
> find node_modules/ -name "*.info" -type f -delete && bower install --allow-root && cd pattern-lab && composer install --no-interaction

bower                           EACCES EACCES: permission denied, mkdir '/Users/cristinallamas/.cache/bower'

Stack trace:
Error: EACCES: permission denied, mkdir '/Users/cristinallamas/.cache/bower'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at sync (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/bower-registry-client/node_modules/mkdirp/index.js:55:12)
    at sync (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/bower-registry-client/node_modules/mkdirp/index.js:61:24)
    at sync (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/bower-registry-client/node_modules/mkdirp/index.js:61:24)
    at Function.sync (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/bower-registry-client/node_modules/mkdirp/index.js:61:24)
    at new Cache (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/bower-registry-client/lib/util/Cache.js:21:16)
    at RegistryClient.<anonymous> (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/bower-registry-client/lib/lookup.js:162:35)
    at Array.forEach (native)
    at RegistryClient.initCache (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/bower-registry-client/lib/lookup.js:149:34)

Console trace:
Error
    at StandardRenderer.error (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/cristinallamas/Sites/agata8/themes/pattern-lab-starter/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 6.5.0
OS: Darwin 15.6.0 x64

npm WARN PatternLabStarter@8.2.1 No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! PatternLabStarter@8.2.1 postinstall: `find node_modules/ -name "*.info" -type f -delete && bower install --allow-root && cd pattern-lab && composer install --no-interaction`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PatternLabStarter@8.2.1 postinstall script 'find node_modules/ -name "*.info" -type f -delete && bower install --allow-root && cd pattern-lab && composer install --no-interaction'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PatternLabStarter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     find node_modules/ -name "*.info" -type f -delete && bower install --allow-root && cd pattern-lab && composer install --no-interaction
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PatternLabStarter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PatternLabStarter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by gerboy** [comment]
Hi Cristina,

i had the same problem, and i typed the commands by hand on the Terminal like this:
find node_modules/ -name "*.info" -type f -delete
bower install --allow-root
cd pattern-lab

when it needs to continue with the sympony 2 installation, composer install --no-interaction , i should change the permision dir /cache to continue and finish the installation at last.

sudo chmod 777 -R /Users/administrador/.composer/cache/

hope it works for you.

**Comment by illepic** [comment]
@cristinallamas, it looks like you potentially ran node or bower as admin at some point and need to manually remove your ~/.cache directory (I'm guessing based on the above output). Then re-run `npm install`.

You'll note that the above command (`find node_modules/ -name \"*.info\" -type f -delete`) is already baked into the npm install.

Can you verify for me that you have no installed node via `sudo`? We highly recommend installing and managing node via [nvm](https://github.com/creationix/nvm) to help avoid this.

**Comment by gerboy** [comment]
@illepic Hi Christopher! i think it's the same to me, i run as root npm one time, so thanks for claryfing it. i'll try nvm too. Thanks for the pattern-lab-starter. 👍

**Comment by illepic** [comment]
I think we can close this issue down now. Please let us know if there are any further install issues.
