### ISSUE TITLE
browersync rewriterules setting failing default npm start

### ISSUE THREAD

**Issue by illepic** [phase2/pattern-lab-starter#58]
Error on fresh install and `npm start`:

````bash
[00:17:39] Starting 'watch:pl:scss-to-json'...
[00:17:39] Starting 'watch:pl'...
[00:17:39] 'serve' errored after 54 ms
[00:17:39] TypeError: bs.options.get(...).forEach is not a function
    at Object.getSnippetMiddleware (/home/illepic/dev/downfall-guild/project/build/dev/d8/themes/custom/patternlab/node_modules/browser-sync/lib/server/utils.js:201:40)
    at Object.getMiddlewares (/home/illepic/dev/downfall-guild/project/build/dev/d8/themes/custom/patternlab/node_modules/browser-sync/lib/server/utils.js:86:37)
    at Object.getBaseApp (/home/illepic/dev/downfall-guild/project/build/dev/d8/themes/custom/patternlab/node_modules/browser-sync/lib/server/utils.js:175:39)
    at createServer (/home/illepic/dev/downfall-guild/project/build/dev/d8/themes/custom/patternlab/node_modules/browser-sync/lib/server/static-server.js:73:27)
    at createServer (/home/illepic/dev/downfall-guild/project/build/dev/d8/themes/custom/patternlab/node_modules/browser-sync/lib/server/index.js:91:42)
    at module.exports.plugin (/home/illepic/dev/downfall-guild/project/build/dev/d8/themes/custom/patternlab/node_modules/browser-sync/lib/server/index.js:16:20)
    at Object.startServer [as fn] (/home/illepic/dev/downfall-guild/project/build/dev/d8/themes/custom/patternlab/node_modules/browser-sync/lib/async.js:195:52)
    at /home/illepic/dev/downfall-guild/project/build/dev/d8/themes/custom/patternlab/node_modules/browser-sync/lib/browser-sync.js:149:14
    at iterate (/home/illepic/dev/downfall-guild/project/build/dev/d8/themes/custom/patternlab/node_modules/browser-sync/lib/utils.js:271:13)
    at /home/illepic/dev/downfall-guild/project/build/dev/d8/themes/custom/patternlab/node_modules/browser-sync/lib/utils.js:280:25
[00:17:39] 'default' errored after 1.17 s
[00:17:39] The following tasks did not complete: watch, watch:icons, watch:js, watch:css, watch:pl:scss-to-json, watch:pl
[00:17:39] Did you forget to signal async completion?
````

Looking into it.

**Comment by illepic** [comment]
Pull request within p2-theme-core fixes this here: https://github.com/phase2/p2-theme-core/pull/19
